<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-15T18:51:12 IST" name="internetBankingV1" finished-at="2023-09-15T18:51:23 IST" duration-ms="10935">
    <groups>
    </groups>
    <test started-at="2023-09-15T18:51:12 IST" name="bankingAppTest" finished-at="2023-09-15T18:51:23 IST" duration-ms="10935">
      <class name="com.banking.testCase.TC_LoginTest_001">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.banking.testCase.TC_LoginTest_001@1608bcbd]" started-at="2023-09-15T18:51:12 IST" name="setUp" finished-at="2023-09-15T18:51:18 IST" duration-ms="6044" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:0, instance:com.banking.testCase.TC_LoginTest_001@1608bcbd]" started-at="2023-09-15T18:51:18 IST" name="loginTest" finished-at="2023-09-15T18:51:21 IST" duration-ms="3274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="validUrl()[pri:0, instance:com.banking.testCase.TC_LoginTest_001@1608bcbd]" started-at="2023-09-15T18:51:21 IST" name="validUrl" finished-at="2023-09-15T18:51:23 IST" depends-on-methods="com.banking.testCase.TC_LoginTest_001.loginTest" duration-ms="1361" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
at com.banking.testCase.TC_LoginTest_001.validUrl(TC_LoginTest_001.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUrl -->
        <test-method signature="checkCourse()[pri:0, instance:com.banking.testCase.TC_LoginTest_001@1608bcbd]" started-at="2023-09-15T18:51:23 IST" name="checkCourse" finished-at="2023-09-15T18:51:23 IST" depends-on-methods="com.banking.testCase.TC_LoginTest_001.validUrl" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.banking.testCase.TC_LoginTest_001.checkCourse() on instance com.banking.testCase.TC_LoginTest_001@1608bcbd depends on not successfully finished methods 
[com.banking.testCase.TC_LoginTest_001.validUrl() on instance com.banking.testCase.TC_LoginTest_001@1608bcbd]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.banking.testCase.TC_LoginTest_001.checkCourse() on instance com.banking.testCase.TC_LoginTest_001@1608bcbd depends on not successfully finished methods 
[com.banking.testCase.TC_LoginTest_001.validUrl() on instance com.banking.testCase.TC_LoginTest_001@1608bcbd]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCourse -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.banking.testCase.TC_LoginTest_001@1608bcbd]" started-at="2023-09-15T18:51:23 IST" name="tearDown" finished-at="2023-09-15T18:51:23 IST" duration-ms="142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.banking.testCase.TC_LoginTest_001 -->
    </test> <!-- bankingAppTest -->
  </suite> <!-- internetBankingV1 -->
</testng-results>
